language: node_js
node_js:
  - "14.16.0"

branches:
  only:
    - master

  addons:
    chrome: stable
    sonarcloud:
    organization: "comunidad-de-programadores"
    token:
      secure: "41de873e38b14970e5ba934d9eeb0bf15d971499" # encrypted value of your token

  before_script:
    - npm install -g @angular/cli

  cache:
    npm: true
    directories:
      - node_modules

script:
  - ng build --prod
  - sonar-scanner

