language: node_js
node_js:
  - "14.16.0"

branches:
  only:
    - master

  addons:
    chrome: stable
    sonarcloud:
    organization: "comunidad-de-programadores"
    token:
      secure: "SONAR_TOKEN" # encrypted value of your token

  before_script:
    - npm install -g @angular/cli

  cache:
    npm: true
    directories:
      - node_modules

script:
  - ng build --prod
  - sonar-scanner

  deploy:
    skip-cleanup: true
    keep-history: true
    local-dir: ./Eventually/Frontend/
