language: node_js
node_js:
- 14.16.0

install:
  - npm ci

addons:
  sonarcloud:
    organization: "comunidad-de-programadores"
    token:
      secure: "**************************" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
